---

galaxy_info:
  author: Vikash Kothary
  description: Installs ROS
  company: "Vikash Kothary"
  license: "MIT"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
    - cloud
    - development
    - system
    - python
dependencies: []